# Site settings
title: Wenzhuo Xu
subtitle: PhD Candidate in Mechanical Engineering
email: wzxu@cmu.edu
description: >- 
  Personal website of Wenzhuo Xu, PhD Candidate at Carnegie Mellon University 
  specializing in machine learning and computational fluid dynamics.
baseurl: "" 
url: "http://wenzhuoxu.com" 

# Social profiles
github_username: WenzhuoXu

# Theme settings
# Using remote theme instead of gem-based theme for better GitHub Pages compatibility
remote_theme: mmistakes/minimal-mistakes@4.24.0
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site structure
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll-include-cache

# Minimal Mistakes specific settings
include:
  - _pages

# Author information
author:
  name   : "Wenzhuo Xu"
  avatar : "/assets/images/self_image.jpg"
  bio    : "PhD Candidate in Mechanical Engineering at Carnegie Mellon University"
  location: "Pittsburgh, PA"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:wzxu@cmu.edu"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/WenzhuoXu"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/wenzhuo-xu-174592110/"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=3RqGjxwAAAAJ&hl=en&oi=ao"

# Navigation links
defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true

# Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/WenzhuoXu"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/wenzhuo-xu-174592110/"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=3RqGjxwAAAAJ&hl=en&oi=ao"